[package]
name = "scog"
version = "0.1.0"
edition = "2024"

[dependencies]
clap_complete = "4.5.59"
clap = { version = "4.5.50", features = ["string", "derive"] }
serde = { version = "1.0.228", features = ["derive"] }
serde-saphyr = "0.0.6"
anyhow = "1.0.100"
termimad = "0.34.0"
